### ISSUE TITLE
Generalize Hausdorff/Apart and Discrete/Tight to Distal/Proximal via Yoneda embedding

### ISSUE THREAD

**Issue by freebroccolo** [freebroccolo/purescript-synthetic-orders#1]
It's obvious by looking at the instances that there should be deeper underlying abstractions because if you switch out the operators and the bounds, you get the same programs:

```purescript
instance hausdorffArray :: (Hausdorff a) => Hausdorff [a] where
  (>~<) []     []     = diverge
  (>~<) (x:xs) (y:ys) = (x >~< y) \~/ (xs >~< ys)
  (>~<) _      _      = yes
```

```purescript
instance apartArray :: (Apart a) => Apart [a] where
  (>.<) []     []     = false
  (>.<) (x:xs) (y:ys) = (x >.< y) \./ (xs >.< ys)
  (>.<) _      _      = true
```

The difference is in the fact that there are more instances definable for `Hausdorff` than there are for `Apart` and this has to do with the lattice structure. For starters, given the relation `(>?<) :: forall a. a -> a -> v`, we need `v` to be a _frame_ i.e., a complete Heyting algebra.

A frame isn't quite enough though because we also need to be able to _stage_ the operations some how:

```purescript
instance hausdorffStream :: (Hausdorff a) => Hausdorff (Stream a) where
  (>~<) (Stream x xs) (Stream y ys) = (x >~< y) \~/ (later \_ -> force xs >~< force ys)
```

Here `later` is an operation for `Time`, which is an approximation of "the" completely iterative free monad. It is defined the same way as `Trampoline` but the intended usage is somewhat different because of `never`. Essentially it used as a scheduler.

If we squint a little bit, it looks like the use of `later` and `force` can be replaced with something like `callCC`. Indeed, the computational interpretation of overt and compact spaces induce modal operators `dia`/`box` which follow a similar pattern. The connection to continuations is apparently justified by Taylor in terms of frame homomorphisms, Sober spaces, and the Yoneda embedding `($ x)`, which I only just realized by accident…

So it seems like a generalization wrt to sobriety is the key to unifying these classes for `Boolean`, `Observe`, and other frames. More general apartness/nearness classes might be called `Distal` and `Proximal` in that case (following "proximity spaces").

**Comment by freebroccolo** [comment]
I've gone ahead and updated `purescript-topologies` to use `Codensity` for quantification as a generalization of `Open a = a -> Sierpinski`. This lets us do really cool things like requesting a witness satisfying some observable property from an overt space:

```purescript
> (any :: (Boolean -> _) -> _) \x -> (any :: (Boolean -> _) -> _) \y -> prompt ((x || y) && not (x && y)) *> now (Tuple x y)
Now Tuple (false) (true)
```

**Comment by freebroccolo** [comment]
I'm also thinking that it may not even be necessary to specify the `Time` monad concretely if we use `Codensity`. It may be enough to simply require that we interpret into some `MonadFree m` which happens to be completely iterative…

**Comment by freebroccolo** [comment]
So one potentially interesting idea for an alternative cim to `Time` would be one that accumulated infinite traces of points of observation in the space. If we worked with algebras, another version could let use explore the space in terms of formal neighborhoods and Böhm trees in the style described by Dybjer.

**Comment by freebroccolo** [comment]
I've tried a few things and it is feasible to generalize these classes as described in the initial comment.

The idea is to start with something like `Posite v a` which is a generalization of poset to a site (in the topos theoretic sense). For our purposes, we only really care that we have an operation `<-= :: a -> a -> v`. In the above cases, `v` would either be `Observe` or `Boolean` then.

However, because the `Lattice` and `Frame` classes depend on `Poset`, and `v` is not mentioned in the types for those operations, generalizing in this way makes all of the lattice operations cumbersome to use. We either have to pass around a proxy like `data Site v = Site` to select the proper instance or we need something like associated types or functional dependencies to relate `a` to `v`. So I guess this is something to keep in mind but it's probably not worth the hassle for now unless I'm missing something obvious…

@paf31 do you have any thoughts about this? Is there another way to work around this?

**Comment by paf31** [comment]
I'm afraid this is way above my familiarity level right now. I'd love to contribute though, and I'm working through Martin Escardo's book again so that I might be able to. Maybe we can discuss at LambdaConf?

**Comment by freebroccolo** [comment]
Sure, sounds good :)
